name: Cpplint

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  cpplint:
    name: Cpplint
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install cpplint
      run: |
        python -m pip install --upgrade pip
        pip install cpplint
    
    - name: Run cpplint
      run: cpplint --extensions=c,h --filter=-legal/copyright,-readability/casting,-build/include_subdir --recursive ./src/lib ./src/libuiohook/src 