name: Cpplint

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  cpplint:
    name: Cpplint
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install cpplint
      run: |
        pip install cpplint
    
    - name: Run cpplint
      run: |
        find ./src -type f -name "*.c" -o -name "*.h" | xargs cpplint --filter=-legal/copyright,-readability/casting,-build/include_subdir || echo "Cpplint found issues but continuing" 